package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	hookBeginMarker = "# BEGIN bark hook"
	hookEndMarker   = "# END bark hook"
)

var hookContents = map[string]string{
	"pre-commit": `#!/bin/sh
# BEGIN bark hook
# Generated by bark - https://github.com/debkanchan/bark
echo "🐕 Running bark to check for BARK comments..."
STAGED=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$STAGED" ]; then
    exit 0
fi
BARKDIR=$(mktemp -d)
trap "rm -rf $BARKDIR" EXIT
for f in $STAGED; do
    mkdir -p "$BARKDIR/$(dirname "$f")"
    git show ":$f" > "$BARKDIR/$f"
done
bark "$BARKDIR"
if [ $? -eq 1 ]; then
    echo ""
    echo "❌ Commit blocked: BARK comments found"
    echo "Please remove BARK comments before committing"
    echo "Run 'bark .' to see all BARK comments"
    exit 1
fi
# END bark hook
`,
	"pre-push": `#!/bin/sh
# BEGIN bark hook
# Generated by bark - https://github.com/debkanchan/bark
echo "🐕 Running bark to check for BARK comments..."
bark .
if [ $? -eq 1 ]; then
    echo ""
    echo "❌ Push blocked: BARK comments found"
    echo "Please remove BARK comments before pushing"
    echo "Run 'bark .' to see all BARK comments"
    exit 1
fi
# END bark hook
`,
}

func installGitHook(hookName string) {
	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "Error: Not in a git repository\n")
		fmt.Fprintf(os.Stderr, "Please run this command from the root of your git repository\n")
		os.Exit(exitError)
	}

	hookPath := filepath.Join(".git", "hooks", hookName)
	content := hookContents[hookName]

	if _, err := os.Stat(hookPath); err == nil {
		timestamp := time.Now().Format("20060102-150405")
		backupPath := hookPath + ".bak." + timestamp

		existing, err := os.ReadFile(hookPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading existing hook: %v\n", err)
			os.Exit(exitError)
		}
		if err := os.WriteFile(backupPath, existing, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error creating backup: %v\n", err)
			os.Exit(exitError)
		}
		fmt.Printf("📦 Backed up existing hook to: %s\n", backupPath)
	}

	var existingContent string
	if existing, err := os.ReadFile(hookPath); err == nil {
		existingContent = string(existing)
	}

	var newContent string

	if strings.Contains(existingContent, hookBeginMarker) &&
		strings.Contains(existingContent, hookEndMarker) {
		lines := strings.Split(existingContent, "\n")
		var result []string
		inBarkSection := false
		replaced := false

		for _, line := range lines {
			if strings.Contains(line, hookBeginMarker) {
				if !replaced {
					result = append(result, strings.TrimSuffix(content, "\n"))
					replaced = true
				}
				inBarkSection = true
				continue
			}
			if strings.Contains(line, hookEndMarker) {
				inBarkSection = false
				continue
			}
			if !inBarkSection {
				result = append(result, line)
			}
		}
		newContent = strings.Join(result, "\n")
		fmt.Println("✅ Updated existing bark hook section")
	} else if existingContent != "" {
		newContent = strings.TrimRight(existingContent, "\n") + "\n\n" + content
		fmt.Printf("✅ Added bark hook to existing %s hook\n", hookName)
	} else {
		newContent = content
		fmt.Printf("✅ Created new %s hook with bark\n", hookName)
	}

	if err := os.WriteFile(hookPath, []byte(newContent), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing hook file: %v\n", err)
		os.Exit(exitError)
	}

	action := "push"
	if hookName == "pre-commit" {
		action = "commit"
	}
	fmt.Printf("\n🎉 Git %s hook installed successfully!\n", hookName)
	fmt.Printf("Bark will now check for BARK comments before each %s\n", action)
	if hookName == "pre-commit" {
		fmt.Println("This hook works with GitHub Desktop and other Git clients")
	}
}

func uninstallGitHook(hookName string) {
	hookPath := filepath.Join(".git", "hooks", hookName)

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Printf("ℹ️  No %s hook found - nothing to uninstall\n", hookName)
		os.Exit(exitSuccess)
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading hook file: %v\n", err)
		os.Exit(exitError)
	}

	hookStr := string(content)

	if !strings.Contains(hookStr, hookBeginMarker) || !strings.Contains(hookStr, hookEndMarker) {
		fmt.Printf("ℹ️  No bark hook found in %s - nothing to uninstall\n", hookName)
		os.Exit(exitSuccess)
	}

	timestamp := time.Now().Format("20060102-150405")
	backupPath := hookPath + ".bak." + timestamp
	if err := os.WriteFile(backupPath, content, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating backup: %v\n", err)
		os.Exit(exitError)
	}
	fmt.Printf("📦 Backed up existing hook to: %s\n", backupPath)

	sc := bufio.NewScanner(strings.NewReader(hookStr))
	var result []string
	inBarkSection := false

	for sc.Scan() {
		line := sc.Text()
		if strings.Contains(line, hookBeginMarker) {
			inBarkSection = true
			continue
		}
		if strings.Contains(line, hookEndMarker) {
			inBarkSection = false
			continue
		}
		if !inBarkSection {
			result = append(result, line)
		}
	}

	newContent := strings.TrimSpace(strings.Join(result, "\n"))

	if newContent == "" || newContent == "#!/bin/sh" || newContent == "#!/bin/bash" {
		if err := os.Remove(hookPath); err != nil {
			fmt.Fprintf(os.Stderr, "Error removing hook file: %v\n", err)
			os.Exit(exitError)
		}
		fmt.Printf("✅ Removed %s hook (file was empty after bark removal)\n", hookName)
	} else {
		if err := os.WriteFile(hookPath, []byte(newContent+"\n"), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing hook file: %v\n", err)
			os.Exit(exitError)
		}
		fmt.Printf("✅ Removed bark section from %s hook\n", hookName)
	}

	fmt.Printf("\n🎉 Bark %s hook uninstalled successfully!\n", hookName)
}
